title: Columbia Young Professionals
description: Participation policies for events hosted by 10x Software LLC (DBA Columbia Young Professionals).
theme: jekyll-theme-primer
url: https://eventops.soft-wa.re
baseurl: "/"
home: /columbia-young-professionals/
last_updated: 2026-01-04
